window.ALBOR = {
  matters: {
    "EXP-2026-014": {
      title: "Impugnación de acuerdos de la junta",
      area: "Mercantil",
      status: "abierto",
      summary:
        "Tres socios minoritarios impugnan la ampliación de capital del 12 de marzo. La convocatoria se notificó con ocho días y el administrador votó con conflicto de interés.",
      clientId: "mora",
      court: "Juzgado de lo Mercantil n.º 7 de Barcelona",
      lead: "Jordi Palau",
      opened: "2 abr 2026",
      amount: "420.000 €",
      opponent: "Tomás Mora Beltrán",
      procurador: "Núria Salvat",
      next: "Vista preliminar",
      nextWhen: "14 oct 2026 · 11:30",
      timeline: [
        { when: "2 abr 2026", label: "Encargo y provisión de fondos" },
        { when: "18 abr 2026", label: "Demanda presentada" },
        { when: "3 jun 2026", label: "Contestación del administrador" },
        { when: "22 sep 2026", label: "Auto de admisión de prueba" },
        { when: "14 oct 2026", label: "Vista preliminar" },
      ],
      documents: [
        { name: "Demanda", meta: "PDF · 18 abr" },
        { name: "Acta de la junta de 12 de marzo", meta: "PDF · 2 abr" },
        { name: "Auto de admisión de prueba", meta: "PDF · 22 sep" },
      ],
    },
    "EXP-2026-019": {
      title: "Impugnación de despido colectivo",
      area: "Laboral",
      status: "urgente",
      summary:
        "Defendemos el ERE de 64 personas. La sección sindical alega que el periodo de consultas se abrió sin las cuentas provisionales. La contestación vence mañana.",
      clientId: "nou",
      court: "Juzgado de lo Social n.º 12 de Barcelona",
      lead: "Marina Soler",
      opened: "15 sep 2026",
      amount: "Sin cuantía",
      opponent: "Sección sindical de CCOO",
      procurador: "Núria Salvat",
      next: "Presentar contestación a la demanda",
      nextWhen: "8 oct 2026 · 13:00",
      timeline: [
        { when: "2 jun 2026", label: "Inicio del periodo de consultas" },
        { when: "28 jul 2026", label: "Acuerdo parcial con UGT" },
        { when: "15 sep 2026", label: "Demanda de impugnación" },
        { when: "8 oct 2026", label: "Vencimiento de la contestación" },
      ],
      documents: [
        { name: "Borrador de contestación v3", meta: "DOCX · ayer" },
        { name: "Memoria del periodo de consultas", meta: "PDF · 28 jul" },
        { name: "Demanda de la sección sindical", meta: "PDF · 15 sep" },
      ],
    },
    "EXP-2025-088": {
      title: "Liquidación de sociedad de gananciales",
      area: "Familia",
      status: "abierto",
      summary:
        "Inventario pendiente de cierre. El desacuerdo está en la vivienda de Sant Gervasi y en unas participaciones que él considera privativas.",
      clientId: "elena",
      court: "Juzgado de Primera Instancia n.º 28 de Barcelona",
      lead: "Clara Nieto",
      opened: "11 nov 2025",
      amount: "860.000 €",
      opponent: "Marc Riera Font",
      procurador: "Pere Coll",
      next: "Enviar propuesta de inventario",
      nextWhen: "16 oct 2026",
      timeline: [
        { when: "11 nov 2025", label: "Demanda de formación de inventario" },
        { when: "4 feb 2026", label: "Comparecencia, sin acuerdo" },
        { when: "1 oct 2026", label: "Tasación de la vivienda recibida" },
        { when: "16 oct 2026", label: "Propuesta de inventario a la otra parte" },
      ],
      documents: [
        { name: "Tasación Sant Gervasi", meta: "PDF · 1 oct" },
        { name: "Escritura de capitulaciones", meta: "PDF · 11 nov 2025" },
        { name: "Extracto de participaciones", meta: "XLSX · 18 sep" },
      ],
    },
    "EXP-2026-011": {
      title: "Licencia de terraza denegada",
      area: "Contencioso",
      status: "abierto",
      summary:
        "Recurso contra la denegación de la terraza de verano. El informe municipal mezcla el plano de 2019 con la ordenanza nueva.",
      clientId: "braseria",
      court: "Juzgado Contencioso Administrativo n.º 4 de Barcelona",
      lead: "Adrià Bosch",
      opened: "9 jun 2026",
      amount: "Licencia",
      opponent: "Ajuntament de Sitges",
      procurador: "Pere Coll",
      next: "Alegaciones al expediente administrativo",
      nextWhen: "21 oct 2026",
      timeline: [
        { when: "3 mar 2026", label: "Denegación de la licencia" },
        { when: "9 jun 2026", label: "Interposición del recurso" },
        { when: "28 sep 2026", label: "Expediente administrativo recibido" },
        { when: "21 oct 2026", label: "Vencimiento de alegaciones" },
      ],
      documents: [
        { name: "Expediente administrativo", meta: "PDF · 28 sep" },
        { name: "Ordenanza de terrazas 2024", meta: "PDF · 9 jun" },
        { name: "Plano de la terraza", meta: "PDF · 3 mar" },
      ],
    },
    "EXP-2026-003": {
      title: "Responsabilidad civil del arquitecto",
      area: "Civil",
      status: "abierto",
      summary:
        "Helvetia nos encarga la defensa del asegurado. La cooperativa reclama 190.000 € por filtraciones en la cubierta de un edificio de Gràcia.",
      clientId: "helvetia",
      court: "Juzgado de Primera Instancia n.º 41 de Barcelona",
      lead: "Marina Soler",
      opened: "20 ene 2026",
      amount: "190.000 €",
      opponent: "Cooperativa d'Habitatges Gràcia",
      procurador: "Núria Salvat",
      next: "Revisar el informe pericial de parte",
      nextWhen: "9 oct 2026 · 09:30",
      timeline: [
        { when: "20 ene 2026", label: "Encargo de Helvetia" },
        { when: "14 mar 2026", label: "Contestación a la demanda" },
        { when: "5 oct 2026", label: "Informe pericial contrario recibido" },
        { when: "9 oct 2026", label: "Revisión interna del peritaje" },
      ],
      documents: [
        { name: "Informe pericial de la actora", meta: "PDF · 5 oct" },
        { name: "Póliza de RC profesional", meta: "PDF · 20 ene" },
        { name: "Contestación a la demanda", meta: "PDF · 14 mar" },
      ],
    },
    "EXP-2025-072": {
      title: "Honorarios impagados",
      area: "Civil",
      status: "cerrado",
      summary:
        "Sentencia estimatoria de septiembre. La mutua ya consignó el principal. Queda la tasación de costas, que lleva el procurador.",
      clientId: "llevant",
      court: "Juzgado de Primera Instancia n.º 15 de Barcelona",
      lead: "Clara Nieto",
      opened: "8 may 2025",
      amount: "74.200 €",
      opponent: "Mutua Ponent",
      procurador: "Pere Coll",
      next: "Sin plazo interno",
      nextWhen: "Costas en manos del procurador",
      timeline: [
        { when: "8 may 2025", label: "Demanda de reclamación de cantidad" },
        { when: "2 sep 2026", label: "Sentencia estimatoria" },
        { when: "19 sep 2026", label: "Consignación del principal" },
      ],
      documents: [
        { name: "Sentencia", meta: "PDF · 2 sep" },
        { name: "Facturas de la clínica", meta: "PDF · 8 may 2025" },
      ],
    },
  },
  clients: {
    mora: {
      name: "Mora & Hijos S.L.",
      sector: "Distribución alimentaria",
      contact: "Núria Mora",
      role: "Socia y administradora",
      email: "nuria.mora@morahijos.example",
      phone: "934 00 18 20",
      address: "Carrer de Pujades 112, Barcelona",
      note: "Las comunicaciones de la impugnación no se copian a Tomás Mora. Núria prefiere llamada antes que correo.",
    },
    nou: {
      name: "Nou Transport S.A.",
      sector: "Logística",
      contact: "Ricard Puig",
      role: "Dirección jurídica",
      email: "ricard.puig@noutransport.example",
      phone: "932 55 40 10",
      address: "Carrer Número 48, Zona Franca",
      note: "Hay que cerrar la contestación con Ricard antes de las 11:00 de mañana. El consejo se reúne a mediodía.",
    },
    elena: {
      name: "Elena Vives Riera",
      sector: "Particular",
      contact: "Elena Vives",
      role: "Clienta",
      email: "elena.vives@correo.example",
      phone: "600 18 44 21",
      address: "Carrer de Balmes 286, Barcelona",
      note: "Pide que las propuestas de inventario le lleguen en papel, además del correo.",
    },
    braseria: {
      name: "Braseria del Port S.L.",
      sector: "Hostelería",
      contact: "Joana Vidal",
      role: "Gerente",
      email: "joana.vidal@braseriadelport.example",
      phone: "938 94 22 07",
      address: "Passeig de la Ribera 14, Sitges",
      note: "La terraza es la mitad de la facturación de julio y agosto. Quiere saber esta semana si hay medida cautelar posible.",
    },
    helvetia: {
      name: "Helvetia Seguros",
      sector: "Aseguradora",
      contact: "Olga Serra",
      role: "Siniestros, RC profesional",
      email: "olga.serra@helvetia.example",
      phone: "933 10 62 45",
      address: "Avinguda Diagonal 550, Barcelona",
      note: "Llamada hoy a las 16:30 para acotar si encargamos perito de parte.",
    },
    llevant: {
      name: "Clínica Llevant",
      sector: "Sanidad",
      contact: "Andreu Feliu",
      role: "Gerencia",
      email: "andreu.feliu@clinicallevant.example",
      phone: "932 08 77 30",
      address: "Carrer de Mandri 62, Barcelona",
      note: "Asunto cerrado en lo sustancial. Solo esperan el importe de costas.",
    },
  },
};
